version: '2.3'

services:

    postgresql-postgis:
        image: mdillon/postgis
        restart: always
        ports:
            - 5000:${POSTGRES_PORT}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - pgdata_test:/var/lib/postgresql/data

    app-uwsgi-server:
        depends_on:
            - postgresql-postgis
        image: protyom/test_react_docker:pip
        volumes:
            - .:/app
        ports:
            - 80:8000
        env_file:
            - .env
        environment:
            - POSTGRES_ADDR=postgresql-postgis
            - REDIS_ADDR=redis
        tty: true
        command: python3 /app/manage.py runserver 0.0.0.0:8000


volumes:
    pgdata_test:
